// Generated by CoffeeScript 1.3.3
(function() {
  var Pool, redback, redis, redis_auth;

  redis_auth = require('../config').redis_auth;
  redis_host = require('../config').redis_server_for_sessions_host;
  redis_port = require('../config').redis_server_for_sessions_port;

  exports.redis = redis = require('redis').createClient(redis_port,redis_host);

  redis.on('error', function(err) {
    return console.error(err);
  });

  if (redis_auth) {
    redis.auth(redis_auth,function(err){
        return console.error(err)
    });
  }

  exports.redback = redback = require('redback').createClient();

  redback.client.on('error', function(err) {
    return console.error(err);
  });

  if (redis_auth) {
    redback.client.auth(redis_auth);
  }

  exports.proxies_set = redback.createSet('keys:connections');

  Pool = require('./pool');

  exports.proxies = new Pool();

}).call(this);
