// Generated by CoffeeScript 1.3.3
(function() {
  var Pool, redback, redis, redis_auth, redis_host, redis_port;

  var config = require('../config');
  redis_auth = config.redis_auth;
  redis_host = config.redis_host;
  redis_port = config.redis_port;

  exports.redis = redis = require('redis').createClient(redis_port, redis_host);

  redis.on('error', function(err) {
    console.error(err);
  });

  if (redis_auth) {
    redis.auth(redis_auth, function(err) {
      console.error('Unable to authenticate redis: set redis_auth in config.json to the value of requirepass in /etc/redis.conf');
      console.error(err);
    });
  }

  exports.redback = redback = require('redback').createClient(redis_port, redis_host);

  redback.client.on('error', function(err) {
    console.error(err);
  });

  if (redis_auth) {
    redback.client.auth(redis_auth);
  }

  exports.proxies_set = redback.createSet('keys:connections');

  Pool = require('./pool');

  exports.proxies = new Pool();

}).call(this);
