// Generated by CoffeeScript 1.3.3
(function() {
  var Pool;

  module.exports = Pool = (function() {

    function Pool(pool) {
      this.pool = pool != null ? pool : {};
    }

    Pool.prototype.get = function(key) {
      return this.pool[key];
    };

    Pool.prototype.set = function(key, val) {
      return this.pool[key] = val;
    };

    Pool.prototype.del = function(key) {
      var val;
      val = this.pool[key];
      delete this.pool[key];
      return val;
    };

    return Pool;

  })();

}).call(this);
