// Generated by CoffeeScript 1.3.3
(function() {
  var connections;

  connections = require('./connections');

  exports.get = function(req, res) {
    return connections.get(req.sessionID, function(err, connections) {
      if (err) {
        res.send({
          error: err.message
        });
        return;
      }
      return res.send(connections);
    });
  };

  exports.post = function(req, res) {
    var connection;
    return connections.post(req.sessionID, connection = req.body, function(err, connection) {
      if (err) {
        res.send({
          error: err.message
        });
        return;
      }
      return res.send(connection);
    });
  };

  exports.del = function(req, res) {
    var id;
    return connections.del(req.sessionID, id = req.params.id, function(err, reply) {
      if (err) {
        res.send({
          error: err.message
        });
        return;
      }
      return res.send(!!reply);
    });
  };

}).call(this);
