// Generated by CoffeeScript 1.3.3
(function() {
  var crypto;

  crypto = require('crypto');

  exports.sha1 = function(data, salt) {
    return crypto.createHmac('sha1', salt).update(data).digest('hex');
  };

  exports.md5 = function(data) {
    return crypto.createHash('md5').update(data).digest('hex');
  };

  exports.base64 = function(value) {
    return new Buffer(value).toString('base64');
  };

}).call(this);
